# Configuration file for piPACT reference collection software
# modified by me

# Settings for iBeacon advertisment
advertiser:
  control_file: 'advertiser_control' # Control file which stops beacon advertisement before timeout
  timeout: 330 # Advertisement timeout (s)
  uuid: '6d032924-5aa1-4e9c-8638-48fcf76da6eb' # UUID, major, and minor values to advertise
  major: 1
  minor: 1 
  tx_power: 0 # Tx power at which to advertise
  interval: 200 # Interval at which advertise (ms)

# Settings for beacon scanner
scanner:
  control_file: 'scanner_control' # Control file which stops beacon scanner before timeout
  scan_prefix: 'scan_output_' # Prefix to attach to scan output files
  timeout: 60 # Scanning timeout (s)
  revisit: 1 # Interval at which to scan (s)
  filters: # Filters
    UUID: 0000fff1-0000-1000-8000-00805f9b34fb # using UUID to filter data so that the scanner ONLY outputs data from the beacon
    
# Logger configuration
logger:
  name: &name 'pi_pact.log'
  config:
    version: 1
    formatters:
      full:
        format: '%(asctime)s   %(module)-10s   %(levelname)-8s   %(message)s'
      brief:
        format: '%(asctime)s   %(levelname)-8s   %(message)s'
    handlers:
      console:
        class: 'logging.StreamHandler'
        level: 'INFO'
        formatter: 'brief'
      file:
        class: 'logging.handlers.TimedRotatingFileHandler'
        level: 'DEBUG'
        formatter: 'full'
        filename: *name
        when: 'H'
        interval: 1
    loggers:
      *name:
        level: 'DEBUG' # Effective logging level
        handlers:
          - 'console'
          - 'file'
